INSERT INTO Laitos (nimi) VALUES ('Fysiikan laitos');
INSERT INTO Laitos (nimi) VALUES ('Geotieteiden ja maantieteen laitos');
INSERT INTO Laitos (nimi) VALUES ('Kemian laitos');
INSERT INTO Laitos (nimi) VALUES ('Matematiikan ja tilastotieteen laitos');
INSERT INTO Laitos (nimi) VALUES ('Tietojenkäsittelytieteen laitos');

INSERT INTO Henkilo (etunimi, sukunimi, tunnus, salasana, laitos, yllapitaja) VALUES ('Mikko', 'Matikka', 'mikka', 'password', 4, FALSE);
INSERT INTO Henkilo (etunimi, sukunimi, tunnus, salasana, laitos, yllapitaja) VALUES ('Outi', 'Olio', 'outolio', '12345', 5, TRUE);
INSERT INTO Henkilo (etunimi, sukunimi, tunnus, salasana, laitos, yllapitaja) VALUES ('Tiina', 'Tutkija', 'tiitu', 'salasana', 2, FALSE);
INSERT INTO Henkilo (etunimi, sukunimi, tunnus, salasana, laitos, yllapitaja) VALUES ('Antti', 'Alkemia', 'antal', '54321', 3, FALSE);
INSERT INTO Henkilo (etunimi, sukunimi, tunnus, salasana, laitos, yllapitaja) VALUES ('Anne', 'Algoritmi', 'alanne', 'qwerty', 5, TRUE);
INSERT INTO Henkilo (etunimi, sukunimi, tunnus, salasana, laitos, yllapitaja) VALUES ('Kari', 'Kartta', 'karita', 'kompassi', 2, FALSE);
INSERT INTO Henkilo (etunimi, sukunimi, tunnus, salasana, laitos, yllapitaja) VALUES ('Minttu', 'Murtoluku', 'murtom', 'funktio', 4, FALSE);
INSERT INTO Henkilo (etunimi, sukunimi, tunnus, salasana, laitos, yllapitaja) VALUES ('Santtu', 'Säteily', 'santsa', 'fysik', 1, FALSE);

INSERT INTO Kurssi (opettaja, nimi, alkuPVM, loppuPVM, laitos) VALUES (1, 'Logiikka I','2015-01-14' , '2015-05-10', 4);
INSERT INTO Kurssi (opettaja, nimi, alkuPVM, loppuPVM, laitos, kysely_aktiivinen) VALUES (4, 'Biologinen kemia', '2014-08-04', '2014-09-15', 3, true);
INSERT INTO Kurssi (opettaja, nimi, alkuPVM, loppuPVM, laitos) VALUES (2,'Ohjelmoinnin perusteet', '2013-09-03', '2013-10-20', 5);
INSERT INTO Kurssi (opettaja, nimi, alkuPVM, loppuPVM, laitos) VALUES (5, 'Tietokantojen perusteet', '2013-09-01', '2013-10-16', 5);
INSERT INTO Kurssi (opettaja, nimi, alkuPVM, loppuPVM, laitos, kysely_aktiivinen) VALUES (2,'Ohjelmoinnin perusteet', '2014-09-01', '2014-10-16', 5, true);
INSERT INTO Kurssi (opettaja, nimi, alkuPVM, loppuPVM, laitos) VALUES (2,'Ohjelmoinnin jatkokurssi', '2013-01-01', '2013-05-28', 5);
INSERT INTO Kurssi (opettaja, nimi, alkuPVM, loppuPVM, laitos) VALUES (6,'Dynaaminen Maa I', '2014-09-01', '2014-11-18', 2);
INSERT INTO Kurssi (opettaja, nimi, alkuPVM, loppuPVM, laitos) VALUES (6,'Ympäristögeologia', '2015-10-03', '2015-04-09', 2);
INSERT INTO Kurssi (opettaja, nimi, alkuPVM, loppuPVM, laitos, kysely_aktiivinen) VALUES (6,'Johdatus Maantieteeseen', '2014-09-01', '2014-10-16', 2, true);
INSERT INTO Kurssi (opettaja, nimi, alkuPVM, loppuPVM, laitos) VALUES (8,'Sähkömagnetismi', '2015-01-14', '2015-02-25', 1);
INSERT INTO Kurssi (opettaja, nimi, alkuPVM, loppuPVM, laitos) VALUES (1, 'Logiikka I','2013-01-14' , '2013-05-05', 4);

INSERT INTO Kysymys (kysymys,vastLaji) VALUES ('Mikä oli tärkein asia minkä opit?', 1);
INSERT INTO Kysymys (kysymys,vastLaji,kaikille) VALUES ('Mikä oli kurssin vaikeustaso?', 2, TRUE);
INSERT INTO Kysymys (kysymys,vastLaji,laitos) VALUES ('Oliko harjoituksissa tarpeeksi tehtäviä?', 2, 4);
INSERT INTO Kysymys (kysymys,vastLaji,kaikille) VALUES ('Kuinka hyödyllinen kurssi mielestäsi oli?', 2, TRUE);
INSERT INTO Kysymys (kysymys,vastLaji,vaihtoehdot) VALUES ('Mikä kokeen tehtävistä oli vaikein?',3, '{1,2,3,4,5,6,7}');
INSERT INTO Kysymys (kysymys,vastLaji,vaihtoehdot) VALUES ('Mikä adjektiivi kuvailisi parhaiten opetusmonistetta?',3, '{"keskeneräinen", "hyödyllinen", "vaikeaselkoinen", "turha", "hauska", "kiinnostava", "omituinen"}');
INSERT INTO Kysymys (kysymys,vastLaji,vaihtoehdot) VALUES ('Oliko tarpeeksi luentoja?', 3, '{oli,ei}');
INSERT INTO Kysymys (kysymys,vastLaji,vaihtoehdot) VALUES ('Oliko tarpeeksi harjoituksia?', 3, '{oli,ei}');
INSERT INTO Kysymys (kysymys,vastLaji) VALUES ('Mitä mieltä olit luennoitsijasta?', 1);
INSERT INTO Kysymys (kysymys,vastLaji,laitos) VALUES ('Mikä maa kiinnostaa eniten tällä hetkellä?', 1, 2);
INSERT INTO Kysymys (kysymys,vastLaji,laitos,vaihtoehdot) VALUES ('Onko kemia hauskaa?', 3, 3, '{on,ei}');

INSERT INTO Kyselykysymys (kurssi, kysymys) VALUES (11,1);
INSERT INTO Kyselykysymys (kurssi, kysymys) VALUES (11,2);
INSERT INTO Kyselykysymys (kurssi, kysymys) VALUES (11,3);
INSERT INTO Kyselykysymys (kurssi, kysymys) VALUES (11,4);
INSERT INTO Kyselykysymys (kurssi, kysymys) VALUES (3,2);
INSERT INTO Kyselykysymys (kurssi, kysymys) VALUES (3,4);
INSERT INTO Kyselykysymys (kurssi, kysymys) VALUES (2,1);
INSERT INTO Kyselykysymys (kurssi, kysymys) VALUES (2,2);
INSERT INTO Kyselykysymys (kurssi, kysymys) VALUES (2,4);
INSERT INTO Kyselykysymys (kurssi, kysymys) VALUES (2,5);
INSERT INTO Kyselykysymys (kurssi, kysymys) VALUES (5,2);
INSERT INTO Kyselykysymys (kurssi, kysymys) VALUES (5,4);
INSERT INTO Kyselykysymys (kurssi, kysymys) VALUES (5,5);
INSERT INTO Kyselykysymys (kurssi, kysymys) VALUES (9,2);
INSERT INTO Kyselykysymys (kurssi, kysymys) VALUES (9,4);
INSERT INTO Kyselykysymys (kurssi, kysymys) VALUES (9,6);
INSERT INTO Kyselykysymys (kurssi, kysymys) VALUES (4,2);
INSERT INTO Kyselykysymys (kurssi, kysymys) VALUES (4,4);
INSERT INTO Kyselykysymys (kurssi, kysymys) VALUES (6,2);
INSERT INTO Kyselykysymys (kurssi, kysymys) VALUES (6,4);

INSERT INTO Vastaus (teksti, k_kysymys) VALUES ('Kaikki lauseet on joko totta tai sitten ei', 1);
INSERT INTO Vastaus (teksti, k_kysymys) VALUES ('On vaikea päätellä asioita loogisesti pätevästi.', 1);
INSERT INTO Vastaus (teksti, k_kysymys) VALUES ('Luonnollisen päättelyn säännöt.', 1);
INSERT INTO Vastaus (teksti, k_kysymys) VALUES ('Tarskin totuusmääritelmä.', 1);
INSERT INTO Vastaus (arvo, k_kysymys) VALUES (5, 2);
INSERT INTO Vastaus (arvo, k_kysymys) VALUES (3, 2);
INSERT INTO Vastaus (arvo, k_kysymys) VALUES (5, 2);
INSERT INTO Vastaus (arvo, k_kysymys) VALUES (1, 2);
INSERT INTO Vastaus (arvo, k_kysymys) VALUES (2, 2);
INSERT INTO Vastaus (arvo, k_kysymys) VALUES (2, 2);
INSERT INTO Vastaus (arvo, k_kysymys) VALUES (5, 3);
INSERT INTO Vastaus (arvo, k_kysymys) VALUES (5, 3);
INSERT INTO Vastaus (arvo, k_kysymys) VALUES (4, 3);
INSERT INTO Vastaus (arvo, k_kysymys) VALUES (5, 3);
INSERT INTO Vastaus (arvo, k_kysymys) VALUES (1, 4);
INSERT INTO Vastaus (arvo, k_kysymys) VALUES (5, 4);
INSERT INTO Vastaus (arvo, k_kysymys) VALUES (5, 4);
INSERT INTO Vastaus (arvo, k_kysymys) VALUES (3, 4);
INSERT INTO Vastaus (arvo, k_kysymys) VALUES (3, 5);
INSERT INTO Vastaus (arvo, k_kysymys) VALUES (4, 5);
INSERT INTO Vastaus (arvo, k_kysymys) VALUES (5, 5);
INSERT INTO Vastaus (arvo, k_kysymys) VALUES (5, 6);
INSERT INTO Vastaus (arvo, k_kysymys) VALUES (4, 6);
INSERT INTO Vastaus (arvo, k_kysymys) VALUES (5, 6);
INSERT INTO Vastaus (arvo, k_kysymys) VALUES (2, 17);
INSERT INTO Vastaus (arvo, k_kysymys) VALUES (2, 17);
INSERT INTO Vastaus (arvo, k_kysymys) VALUES (2, 17);
INSERT INTO Vastaus (arvo, k_kysymys) VALUES (2, 17);
INSERT INTO Vastaus (arvo, k_kysymys) VALUES (2, 17);
INSERT INTO Vastaus (arvo, k_kysymys) VALUES (1, 18);
INSERT INTO Vastaus (arvo, k_kysymys) VALUES (1, 18);
INSERT INTO Vastaus (arvo, k_kysymys) VALUES (2, 18);
INSERT INTO Vastaus (arvo, k_kysymys) VALUES (4, 19);
INSERT INTO Vastaus (arvo, k_kysymys) VALUES (5, 19);
INSERT INTO Vastaus (arvo, k_kysymys) VALUES (4, 19);
INSERT INTO Vastaus (arvo, k_kysymys) VALUES (3, 20);
INSERT INTO Vastaus (arvo, k_kysymys) VALUES (4, 20);
INSERT INTO Vastaus (arvo, k_kysymys) VALUES (4, 20);